name: Node.js CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: self-hosted
    
        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20' # Specify a version that matches your project
        - run: node -v
        - run: npm -v
        - name: Install dependencies
          run: npm install --legacy-peer-deps
        - name: Build application
          run: npm run build
        - name: Stop existing application 
          run: | 
            if netstat -ano | findstr :5000 > nul; then 
              for /f "tokens=5" %a in ('netstat -ano ^| findstr :5000') do taskkill /F /PID %a 
            fi
          continue-on-error: true
        - name: Start the application
          run: | 
            start /B npm run start > app.log 2>&1
