name: Node.js CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: self-hosted
    
        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20' # Specify a version that matches your project
        - run: node -v
        - run: npm -v
        - name: Install dependencies
          run: npm install --legacy-peer-deps
        - name: Build application
          run: npm run build
        - name: Start the application
          run: |
            # Kill any existing process on port 5000 (if needed)
            # pkill -f "node app.js" || true
            # Start the server in the background
            nohup node app.js > app.log 2>&1 &
