name: Node.js CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: self-hosted
    
        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20' # Specify a version that matches your project
        - run: node -v
        - run: npm -v

        - name: Install dependencies
          run: npm install --legacy-peer-deps

        - name: Build application
          env:
            FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
            FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
            FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
            API_URL: ${{ secrets.API_URL }}
          run: npm run build

        - name: Start the application
          env:
            FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
            FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
            FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
            API_URL: ${{ secrets.API_URL }}
          run: | 
            pm2 stop 0
            pm2 start 0
            pm2 save
          shell: bash
